### ISSUE TITLE
iOS7下闪退

### ISSUE THREAD

**Issue by cgcsyao** [leancloud/leancloud-feedback-ios#25]
UIImage *closeButtonImage = [UIImage imageNamed:@"back" inBundle:[NSBundle bundleForClass:[self class]] compatibleWithTraitCollection:nil];

 +[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]: unrecognized selector sent to class 0x109c59120

**Comment by lzwjava** [comment]
请问您是怎样使用这个组件的？

如果是 pod 的话，那得等我们发布新版本了。

如果是 源代码的引入的话，目前可以 把这个：

UIImage *closeButtonImage = [UIImage imageNamed:@"back" inBundle:[NSBundle bundleForClass:[self class]] compatibleWithTraitCollection:nil];

改为

UIImage *closeButtonImage = [UIImage imageNamed:@"back"];

**Comment by lzwjava** [comment]
已发布 0.0.6

更改成 `pod 'LeanCloudFeedback', '0.0.6'` ，更新 pod 即可

请测试。
