### ISSUE TITLE
feedback 还是有大量重复创建的问题。

### ISSUE THREAD

**Issue by tang3w** [leancloud/leancloud-feedback-ios#30]
是不是 UI 上没有处理好造成的？ @lzwjava

**Comment by lzwjava** [comment]
不太可能，应该是还在用老版本的 SDK 的问题。我联系下相关的开发者

**Comment by lzwjava** [comment]
已联系相关的用户，是用户把用户反馈当做统计日志来用，存储很多用户的设备信息。用户允许我们清理这样的反馈。
