### ISSUE TITLE
xcode编译LeanCloudFeedback.framework出来直接使用会报错。

### ISSUE THREAD

**Issue by woodyyan** [leancloud/leancloud-feedback-ios#31]
启动的时候就会直接报错，内容如下：
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (AVUser)'

请问如何解决？

貌似直接使用项目源代码就没有问题。

**Comment by tang3w** [comment]
请给出导致异常的代码片段，以及异常出现时的调用栈。
