### ISSUE TITLE
多語系

### ISSUE THREAD

**Issue by shinrenpan** [leancloud/leancloud-feedback-ios#32]
中文的描述希望使用多語系
例如 [LCUserFeedbackImageViewController.m][1] title 應該使用

```objC
self.title = NSLocalizedString(@"LCUserFeedbackImageViewController_Title", nil);
```

而不是
```objC
self.title = @"詳情";
```

[1]: https://github.com/leancloud/leancloud-feedback-ios/blob/master/LeanCloudFeedback/LCUserFeedbackImageViewController.m#L21

**Comment by lzwjava** [comment]
好的，稍后改进一下。

**Comment by lzwjava** [comment]
0.0.8 已发布
