### ISSUE TITLE
静态库不支持 arm64

### ISSUE THREAD

**Issue by dongeyoung** [leancloud/leancloud-feedback-ios#37]
静态库不支持 arm64, 在编译后会报错!
这个如何解决呢? 在线等.........

检查发现:
lipo -info /Users/dongeyoung/Library/Developer/Xcode/DerivedData/LeanCloudFeedback-ajouwqtvjpvlknerqfoiqejnzbld/Build/Products/Debug-iphoneos/libPods-LeanCloudFeedback.a 
input file /Users/dongeyoung/Library/Developer/Xcode/DerivedData/LeanCloudFeedback-ajouwqtvjpvlknerqfoiqejnzbld/Build/Products/Debug-iphoneos/libPods-LeanCloudFeedback.a is not a fat file
Non-fat file: /Users/dongeyoung/Library/Developer/Xcode/DerivedData/LeanCloudFeedback-ajouwqtvjpvlknerqfoiqejnzbld/Build/Products/Debug-iphoneos/libPods-LeanCloudFeedback.a is architecture: armv7

编译以后:
file was built for archive which is not the architecture being linked (arm64): /Users/dongeyoung/Documents/Life Schedule/Life Schedule/LeanCloudFeedback.framework/LeanCloudFeedback
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_LCUserFeedbackViewController", referenced from:
      type metadata accessor for __ObjC.LCUserFeedbackViewController in SettingTableViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Type metadata accessor for __ObjC.LCUserFeedbackViewController in SettingTableViewController.o
Symbol(s) not found for architecture arm64

**Comment by lzwjava** [comment]
好的，我稍后会看看。

目前的话，你可以直接把源码复制到项目里。因为这里的源码相对来说，比较稳定。你可能一次复制以后，以后再也不用同步了。

**Comment by dongeyoung** [comment]
关键 我用的是 Swift. 导入 AVOSCloud 之后, objc 没法访问 Swift 里面的外部框架...... 提示找不到 AVOSCloud Module.

**Comment by tang3w** [comment]
你好，请提供一下详细的复现问题的步骤。静态库模板同时支持 ARM 和 x86_64 / i386。另外，也可以也可以使用 CocoaPods 来进行集成，具体步骤请参考：

https://github.com/leancloud/leancloud-feedback-ios/issues/36#issuecomment-161175889
