### ISSUE TITLE
使用push形式弹出用户反馈页面，点击反馈后整个界面就变黑

### ISSUE THREAD

**Issue by yanzhiwei147** [leancloud/leancloud-feedback-ios#39]
经查是于IQKeyboardManager这个库相冲突，希望能否改进？
图片上传始终失败，就先不上图了。

**Comment by ChenYilong** [comment]
不清楚冲突的地方是哪里？能否详细描述下

**Comment by yanzhiwei147** [comment]
在测试使用建议反馈的库，因此具体没有详看，一旦启用了IQKeyboardManager的功能就会发生黑屏，目前友盟的建议反馈并不会噢。

**Comment by ChenYilong** [comment]
请问IQKeyboardManager的版本号

**Comment by yanzhiwei147** [comment]
版本号为3.3.4

**Comment by beiguancyc** [comment]
跟这位仁兄情况一样，一点输入栏屏幕变黑。
