### ISSUE TITLE
大部分反馈消息都会发送两次

### ISSUE THREAD

**Issue by imWildCat** [leancloud/leancloud-feedback-ios#41]
![qq20151130-0](https://cloud.githubusercontent.com/assets/2396817/11472990/ecaef644-97aa-11e5-97bb-5816d2dfc0ff.png)

**Comment by ChenYilong** [comment]
可否排除是 App 方面的问题，比如：用户操作，或者 App 里逻辑的错误？

**Comment by imWildCat** [comment]
我刚才又去测试了下，确实不是用户操作的问题。另外逻辑都是你们写的，我没有修改。这个问题应该和 #30 类似。
注：重复的信息似乎在用户端看不到，只是在我的 Leancloud 后台能看到。

**Comment by ChenYilong** [comment]
你看下存储里的 message 表里面，看下 message 是否重复。排除下是否是前端显示的问题。
