### ISSUE TITLE
AVOSCloud 静态库签名导致真机测试老是提示证书出错

### ISSUE THREAD

**Issue by mouse-lin** [leancloud/leancloud-feedback-ios#44]

**Comment by tang3w** [comment]
请问静态库是如何集成的，手动集成还是 CocoaPods 集成？

另外，可以到 AVOSCloud.framework 目录下输入如下命令查看一下二进制文件是否有正确的签名：

```sh
codesign --display --verbose=4 AVOSCloud
```

**Comment by mouse-lin** [comment]
@tang3w 你好，我通过 pod 引入的，动态库

**Comment by tang3w** [comment]
你好，目前动态库集成的问题是 Xcode 的一个 bug 导致的，需要创建一个 Run Script，脚本可以在我们的快速入门文档中找到。

**Comment by eyougo** [comment]
文档地址呢？没找到所谓的快速入门文档的Run Script啊
