### ISSUE TITLE
升级AVOSCloud到3.2.2会报错，退回3.1.7.1就没问题了

### ISSUE THREAD

**Issue by hustlzp** [leancloud/leancloud-feedback-ios#48]
报错和 AVDeprecated 相关。

**Comment by ChenYilong** [comment]
leancloud-feedback-ios 的 pod 库也做了相应更新。请更新下，请问您用的是静态库还是动态库？

**Comment by hustlzp** [comment]
AVOSCloud和leancloud-feedback都是用的静态库。

leancloud-feedback还是很不错的一个插件，希望越做越好 :)

**Comment by ChenYilong** [comment]
pod 已经更新至0.1.0了，该问题已经解决。请问更新后是否还报错？

**Comment by hustlzp** [comment]
没问题了，是我的问题，我更新下pod库就好了。多谢
