### ISSUE TITLE
push出来的时候，输入框没有

### ISSUE THREAD

**Issue by beiguancyc** [leancloud/leancloud-feedback-ios#51]
![simulator screen shot 2016 2 19 3 56 11](https://cloud.githubusercontent.com/assets/12932389/13169600/c126c2de-d721-11e5-910b-8e768404e474.png)

**Comment by beiguancyc** [comment]
LCUserFeedbackViewController *feedbackViewController = [[LCUserFeedbackViewController alloc] init];
    feedbackViewController.feedbackTitle = @"用户反馈";
    feedbackViewController.contact = nil;
    
    // 隐藏联系人表头
    feedbackViewController.contactHeaderHidden = YES;
    
    // 决定返回按钮和样式
    feedbackViewController.presented = NO;
    
    // 不设置导航栏样式
    feedbackViewController.navigationBarStyle = LCUserFeedbackNavigationBarStyleBlue;
    feedbackViewController.hidesBottomBarWhenPushed=YES;
//    feedbackViewController.navigationController.navigationBarHidden=NO;
   
    UITabBarController *tabVC = (UITabBarController *) _navigationController.visibleViewController;
  
    UINavigationController *pushClassStance = (UINavigationController *)tabVC.viewControllers[0];
//    // 跳转到对应的控制器
    [pushClassStance pushViewController:feedbackViewController animated:YES];

**Comment by neil-wu** [comment]
同遇到

**Comment by fdddf** [comment]
+1

**Comment by zhuozhuo** [comment]
我看了它demo是没有问题的，估计是因为不是用的constraints写的所以在- (void)viewDidAppear:(BOOL)animated位置变了：修改方法：
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    if (!_inputTextField) {
        [self setupUI];
        //    [self keyboardWillHide:nil];
        [self loadFeedbackThreads];

    }
}

**Comment by Dada08** [comment]
几个子 view 定义时没有考虑到 navigationitem 的 height，导致 addImageButton、inputTextField、sendButton 的位置超出屏幕了，只需要将这三个 view 的 frame 的 y 减去64即可。

@zhuozhuo 的方法也可行，不过push 的时候会有短暂的卡顿。
