### ISSUE TITLE
Swift 3 + CocoaPods 界面不显示图片

### ISSUE THREAD

**Issue by iTofu** [leancloud/leancloud-feedback-ios#58]
如底部工具栏选择图片的图片、聊天气泡背景图片等都不显示？

**Comment by pandaApe** [comment]
也有同样的问题 —_—

**Comment by YangHang** [comment]
这个问题是由于CocoPods在swift项目下会把leancloud-feedback-ios打包成一个动态库，而动态库有自己的bundle，源代码里的图片是直接通过图片名字在mainbundle里获取，所以就会有问题。可以通过
         
         NSBundle *frameWorkBundle = [NSBundle bundleForClass:[self class]];
         UIImage * closeButtonImage = [UIImage imageNamed:@"feedback_back" 
         inBundle:frameWorkBundle compatibleWithTraitCollection:nil];

来解决这个问题

**Comment by iTofu** [comment]
是的

发自我的 iPhone
