### ISSUE TITLE
请问能不能开放获取反馈的api？

### ISSUE THREAD

**Issue by wyk111wyk** [leancloud/leancloud-feedback-ios#64]
那我就可以做一个客户端获取用户反馈，以及及时回复了。
网页版和你们自己那个真心难用。

**Comment by zapcannon87** [comment]
您好，这是相关文档：https://leancloud.cn/docs/rest_api.html#hash1473482921

**Comment by wyk111wyk** [comment]
感谢～LeanAnalytics没有开源是吗？

**Comment by wyk111wyk** [comment]
另外能不能问一下已完结这个属性是什么意思？对用户有什么影响吗？
